apiVersion: 1.0.0
kind: Plugin
metadata:
  name: CouchDB Storage
  description: CouchDB storage plugin for Reekoh IoT Platform.
  documentation: README.md
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - storage
    - couchdb
  config:
    host:
      label: Host
      type: String
      maxLength: 1000
      required: true
      help: "Host for the CouchDB database connection."
    port:
      label: Port
      type: Number
      min: 1
      max: 65353
      required: true
      help: "Port for the CouchDB database connection."
    connectionType:
      label: Connection Type
      type: String
      maxLength: 1000
      required: true
      enum:
        - http
        - https
      help: "Type of connection to be used."
    user:
      label: User
      type: String
      maxLength: 1000
      required: true
      help: "(Options) User for authentication (Basic Auth)."
    password:
      label: Password
      type: Password
      maxLength: 1000
      required: false
      help: "(Optional) Password for authentication (Basic Auth)."
    database:
      label: Database Name
      type: String
      maxLength: 1000
      required: true
      help: "Database Name where the Collection is located."

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    image: path/to/docker/image # ??